openapi: 3.0.0
info:
  version: 1.0.0
  title: Software Products API
  description: An API to access software product information

servers:
  - url: http://localhost:5000/api
    description: Local development server

paths:
  /api/products:
    get:
      description: Returns a list of software products
      responses:
        '200':
          description: Successfully returned a list of software products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          links:
            self:
              operationRef: '#/paths/~1products~1{id}/get'
              parameters:
                id: '$response.body#/id'
              description: >
                The `id` value returned in the response can be used as
                the `id` parameter in `GET /products/{id}`.
            products.environments:
              operationRef: '#/paths/~1products~1{id}environments/get'
              parameters:
                id: '$response.body#/id'
              description: >
                The `id` value returned in the response can be used as
                the `id` parameter in `GET /products/{id}/environments`.
        '408':
          $ref: '#/components/responses/408Error'
        '500':
          $ref: '#/components/responses/500Error'

  /api/products/{id}:
    get:
      description: Returns a specific product
      operationId: getProduct
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Successfully returned a product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /api/products/{id}/environments:
    get:
      description: Obtain information about a products environments from its unique id
      operationId: getEnvironments
      parameters:
        - $ref: '#/components/parameters/Id'

      responses:
        '200':
          description: Successfully returned a list of environments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Environment'

        '408':
          $ref: '#/components/responses/408Error'
        '500':
          $ref: '#/components/responses/500Error'

components:

  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: The product display name

    Environment:
      type: object
      required:
        - id
        - name
        - status
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: The environment display name
        status:
          type: string
          enum:
            - UP
            - DOWN

  parameters:
    Id:
      name: id
      in: path
      required: true
      description: Limits the number of items on a page
      schema:
        type: string
        format: uuid

  responses:
    408Error:
      description: Request Timeout
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    500Error:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string